<%@page contentType="text/html;charset=UTF-8"%>
 <ul class="menu">
   <li id="oxygen-info" ><a href="controller?go=oxygen-info">Информация</a></li>
   <li id="zerno-form" "><a href="controller?go=zerno-form">Зерно катализатора</a></li>
   <li id="isoterm-form" "><a href="controller?go=isoterm-form">Неподвижный слой</a></li>
   <li id="move-form" "><a href="controller?go=move-form">Движущийся слой</a></li>
 </ul>